from gif_prepare_medcut import _prepare_balanced_medcut_context
from gif_complete_medcut import _complete_balanced_iteration


def _run_balanced_iteration(
    *,
    iteration,
    source,
    state,
    frames_raw,
    durations,
    width,
    height,
    palette_limit,
    total_frames,
    colors_first,
    init_size,
    input_path,
    stats_mgr,
    executor,
    workers,
    target_mid,
    bias_factor,
    small_res_high_frames,
    gif_cfg,
    started_at,
    version,
    debug_log,
):
    med_input = _prepare_balanced_medcut_context(
        iteration=iteration,
        source=source,
        state=state,
        frames_raw=frames_raw,
        durations=durations,
        width=width,
        height=height,
        palette_limit=palette_limit,
        total_frames=total_frames,
        colors_first=colors_first,
        init_size=init_size,
        input_path=input_path,
        stats_mgr=stats_mgr,
        executor=executor,
        workers=workers,
        target_mid=target_mid,
        bias_factor=bias_factor,
        gif_cfg=gif_cfg,
        started_at=started_at,
        version=version,
        debug_log=debug_log,
    )
    if med_input["status"] == "done":
        return {
            "done": True,
            "frames_raw": med_input["frames_raw"],
            "durations": med_input["durations"],
            "total_frames": med_input["total_frames"],
        }
    if med_input["status"] == "continue":
        return {
            "done": False,
            "frames_raw": med_input["frames_raw"],
            "durations": med_input["durations"],
            "total_frames": med_input["total_frames"],
        }

    return _complete_balanced_iteration(
        iteration=iteration,
        state=state,
        med_input=med_input,
        frames_raw=frames_raw,
        durations=durations,
        width=width,
        height=height,
        palette_limit=palette_limit,
        total_frames=total_frames,
        colors_first=colors_first,
        init_size=init_size,
        input_path=input_path,
        stats_mgr=stats_mgr,
        executor=executor,
        workers=workers,
        target_mid=target_mid,
        small_res_high_frames=small_res_high_frames,
        gif_cfg=gif_cfg,
        started_at=started_at,
        version=version,
        debug_log=debug_log,
    )
